### ISSUE TITLE
Appimage start failed in Arch linux

### ISSUE THREAD

**Issue by laxect** [odrevet/gjiten-kai#3]
Version: v0.1.4 (Appimage version)  
error log:
```
❯ ./Gjiten_Kai-x86_64.AppImage

(Gjiten_Kai-x86_64.AppImage:214587): Gtk-CRITICAL **: 12:25:00.385: gtk_builder_add_from_file: assertion 'filename != NULL' failed
Impossible to find UI definition file at !�
(Gjiten_Kai-x86_64.AppImage:214587): Gtk-CRITICAL **: 12:25:00.385: gtk_builder_add_from_file: assertion 'filename != NULL' failed

(Gjiten_Kai-x86_64.AppImage:214587): GLib-GIO-ERROR **: 12:25:00.385: Settings schema 'gjitenkai.worddic' is not installed
zsh: trace trap (core dumped)  ./Gjiten_Kai-x86_64.AppImage
```

**Comment by odrevet** [comment]
The GSettings key 'gjitenkai.worddic', installed in /usr/share/glib-2.0/schemas/gjitenkai.gschema.xml, is compiled and copied during `make install`

While making the appimage there is this error message : 

Failed to create file “/usr/share/glib-2.0/schemas/gschemas.compiled.H4Z870”: Permission denied

So gjitenkai.gschema.xml is indeed missing from the appimage. 
When not present in the appimage filesystem the system will try to find it in the host filesystem, this is why I did not noticed this before

**Comment by laxect** [comment]
Thx for the reply! But this error still exists in the latest release.

```
❯ ./Gjiten_Kai-x86_64.AppImage

(Gjiten_Kai-x86_64.AppImage:266451): Gtk-CRITICAL **: 18:01:53.894: gtk_builder_add_from_file: assertion 'filename != NULL' failed
Impossible to find UI definition file at <U
(Gjiten_Kai-x86_64.AppImage:266451): Gtk-CRITICAL **: 18:01:53.894: gtk_builder_add_from_file: assertion 'filename != NULL' failed

(Gjiten_Kai-x86_64.AppImage:266451): GLib-GIO-ERROR **: 18:01:53.894: Settings schema 'gjitenkai.worddic' is not installed
zsh: trace trap (core dumped)  ./Gjiten_Kai-x86_64.AppImage
```

And I can find `gjitenkai.gschema.xml` in the latest image, so may other things not work?

**Comment by odrevet** [comment]
This is because I did not embed the compiled gsettings into the appimage. 
This *should* be fixed now. You can try again with the new release

**Comment by laxect** [comment]
Still the same error...

```
❯ ./Gjiten_Kai-x86_64.AppImage

(Gjiten_Kai-x86_64.AppImage:451655): Gtk-CRITICAL **: 11:19:29.059: gtk_builder_add_from_file: assertion 'filename != NULL' failed
Impossible to find UI definition file at �QV
(Gjiten_Kai-x86_64.AppImage:451655): Gtk-CRITICAL **: 11:19:29.059: gtk_builder_add_from_file: assertion 'filename != NULL' failed

(Gjiten_Kai-x86_64.AppImage:451655): GLib-GIO-ERROR **: 11:19:29.059: Settings schema 'gjitenkai.worddic' is not installed
zsh: trace trap (core dumped)  ./Gjiten_Kai-x86_64.AppImage
```

**Comment by odrevet** [comment]
I made a new release which I tested on a clean system, should be fine this time!

**Comment by laxect** [comment]
The latest version is still not working.

```
❯ ./Gjiten_Kai-x86_64.AppImage

(gjitenkai_bin:1001261): Gtk-WARNING **: 11:22:33.155: Could not load image '../kai.png': ファイル“/tmp/.mount_GjitenIStkkL/usr/share//gjitenkai/ui/../kai.png”の画像ファイル形式を認識できませんでした

(gjitenkai_bin:1001261): Gtk-WARNING **: 11:22:33.174: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(gjitenkai_bin:1001261): Gtk-WARNING **: 11:22:33.187: Could not load image '../kai.png': ファイル“/tmp/.mount_GjitenIStkkL/usr/share//gjitenkai/ui/../kai.png”の画像ファイル形式を認識できませんでした
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: 認識できない画像ファイル形式 (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: 認識できない画像ファイル形式 (gdk-pixbuf-error-quark, 3)
/tmp/.mount_GjitenIStkkL/AppRun: 6 行: 1001261 中止                  (コアダンプ) $BIN_DIR/gjitenkai_bin "$@"
```

But when I build it myself follow the wiki, it works fine. Maybe some lib behaves differently in those distribution?

**Comment by laxect** [comment]
Anyway, Thanks for your help!
